CREATE DATABASE IF NOT EXISTS `streaming_db`
    DEFAULT CHARACTER SET = `utf8`
    DEFAULT COLLATE = `utf8_general_ci`;

CREATE TABLE IF NOT EXISTS `stream_titles` (
    `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `Creation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `Game` TEXT NOT NULL COLLATE `utf8_bin`,
    `Title` TEXT NOT NULL COLLATE `utf8_bin`,
    `Tags` TEXT DEFAULT NULL COLLATE `utf8_bin`,
    INDEX `SORT` USING BTREE (`Game` (128), `Title` (128))
) ENGINE=INNODB;