//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShinyResetApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShinyResetApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string AttemptDecrementText {
            get {
                return ResourceManager.GetString("AttemptDecrementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string AttemptIncrementText {
            get {
                return ResourceManager.GetString("AttemptIncrementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:mm&apos;:&apos;ss&apos;.&apos;fff}.
        /// </summary>
        internal static string AverageText {
            get {
                return ResourceManager.GetString("AverageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U/N.
        /// </summary>
        internal static string AverageUnavailableText {
            get {
                return ResourceManager.GetString("AverageUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add key {0}!.
        /// </summary>
        internal static string CantCreateKeyErrorText {
            get {
                return ResourceManager.GetString("CantCreateKeyErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t create section {0}!.
        /// </summary>
        internal static string CantCreateSectionErrorText {
            get {
                return ResourceManager.GetString("CantCreateSectionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last click: N/A..
        /// </summary>
        internal static string DetailLabelDefaultText {
            get {
                return ResourceManager.GetString("DetailLabelDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last click {0:mm&apos;:&apos;ss&apos;.&apos;fff}..
        /// </summary>
        internal static string DetailLabelText {
            get {
                return ResourceManager.GetString("DetailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        internal static string ExitToolStripItemText {
            get {
                return ResourceManager.GetString("ExitToolStripItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiny Reset Auto-updater.
        /// </summary>
        internal static string MainFormTitleText {
            get {
                return ResourceManager.GetString("MainFormTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Main.
        /// </summary>
        internal static string MainToolStripItemText {
            get {
                return ResourceManager.GetString("MainToolStripItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,##0}.
        /// </summary>
        internal static string OddsText1 {
            get {
                return ResourceManager.GetString("OddsText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#,##0.00}.
        /// </summary>
        internal static string OddsText2 {
            get {
                return ResourceManager.GetString("OddsText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt|All files|*.*.
        /// </summary>
        internal static string OpenFileDialogFilterText {
            get {
                return ResourceManager.GetString("OpenFileDialogFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average: {0}.
        /// </summary>
        internal static string ResetAverageText {
            get {
                return ResourceManager.GetString("ResetAverageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try {0:#,##0} (≈{1:0.00}%, ≈1 in {2}) → {3:#,##0}.
        /// </summary>
        internal static string ResetCountText {
            get {
                return ResourceManager.GetString("ResetCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string ResetToolStripItemText {
            get {
                return ResourceManager.GetString("ResetToolStripItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to save the reset average details to....
        /// </summary>
        internal static string SelectResetAverageFileText {
            get {
                return ResourceManager.GetString("SelectResetAverageFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file to save the reset count details to....
        /// </summary>
        internal static string SelectResetCountFileText {
            get {
                return ResourceManager.GetString("SelectResetCountFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string SettingsApplyButtonText {
            get {
                return ResourceManager.GetString("SettingsApplyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string SettingsBrowseButtonText {
            get {
                return ResourceManager.GetString("SettingsBrowseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SettingsCancelButtonText {
            get {
                return ResourceManager.GetString("SettingsCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsFormTitleText {
            get {
                return ResourceManager.GetString("SettingsFormTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SettingsOkButtonText {
            get {
                return ResourceManager.GetString("SettingsOkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Average File.
        /// </summary>
        internal static string SettingsResetAverageFileText {
            get {
                return ResourceManager.GetString("SettingsResetAverageFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Count File.
        /// </summary>
        internal static string SettingsResetCountFileText {
            get {
                return ResourceManager.GetString("SettingsResetCountFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings....
        /// </summary>
        internal static string SettingsToolStripItemText {
            get {
                return ResourceManager.GetString("SettingsToolStripItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Resets.
        /// </summary>
        internal static string SettingsTotalResetsText {
            get {
                return ResourceManager.GetString("SettingsTotalResetsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Shinies.
        /// </summary>
        internal static string SettingsTotalShiniesText {
            get {
                return ResourceManager.GetString("SettingsTotalShiniesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - shiny.
        /// </summary>
        internal static string ShinyDecrementText {
            get {
                return ResourceManager.GetString("ShinyDecrementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + shiny.
        /// </summary>
        internal static string ShinyIncrementText {
            get {
                return ResourceManager.GetString("ShinyIncrementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes pending. Would you like to save them now?.
        /// </summary>
        internal static string UnsavedChangesWarningText {
            get {
                return ResourceManager.GetString("UnsavedChangesWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string UnsavedChangesWarningTitleText {
            get {
                return ResourceManager.GetString("UnsavedChangesWarningTitleText", resourceCulture);
            }
        }
    }
}
