
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//     Generated At: Tuesday, March 16, 2021 at 16:29:15
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("WinAudioLevels")]
[assembly: AssemblyDescription("Provides a WebSocket server to allow local web applications to have access to the audio levels on the system.")]
#if DEBUG
[assembly: AssemblyConfiguration("debug")]
#else
[assembly: AssemblyConfiguration("release")]
#endif
[assembly: AssemblyCompany("EmptySora_")]
[assembly: AssemblyProduct("WinAudioLevels")]
[assembly: AssemblyCopyright("Copyright EmptySora_© 2021-2021")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("a51ec718-6d6a-462f-820e-e6426335c1c0")]
[assembly: AssemblyVersion("0.1.4.180")]
[assembly: AssemblyFileVersion("0.1.4.180")]
#if DEBUG
[assembly: AssemblyInformationalVersion("0.1.4.180δα (build #180 at 2021-03-16T20:29:15Z)")]
#else
[assembly: AssemblyInformationalVersion("0.1.4.180ρα (build #180 at 2021-03-16T20:29:15Z)")]
#endif

namespace WinAudioLevels {
    static class AssemblyDetails {
         public const string ASSEMBLY_TITLE = "WinAudioLevels";
         public const string ASSEMBLY_DESCRIPTION = "Provides a WebSocket server to allow local web applications to have access to the audio levels on the system.";
         public const string ASSEMBLY_COMPANY = "EmptySora_";
         public const string ASSEMBLY_PRODUCT = "WinAudioLevels";
         public const string ASSEMBLY_COPYRIGHT = "Copyright EmptySora_© 2021-2021";
         public const string ASSEMBLY_TRADEMARK = "";
         public const string ASSEMBLY_CULTURE = "";
         public const bool COM_VISIBLE = false;
         public const string GUID = "a51ec718-6d6a-462f-820e-e6426335c1c0";
         public const string ASSEMBLY_VERSION = "0.1.4.180";
         public const string ASSEMBLY_FILE_VERSION = "0.1.4.180";
         #if DEBUG
         public const string ASSEMBLY_CONFIGURATION = "debug";
         public const string ASSEMBLY_INFORMATIONAL_VERSION = "0.1.4.180δα (build #180 at 2021-03-16T20:29:15Z)";
         #else
         public const string ASSEMBLY_CONFIGURATION = "release";
         public const string ASSEMBLY_INFORMATIONAL_VERSION = "0.1.4.180ρα (build #180 at 2021-03-16T20:29:15Z)";
         #endif
    }
}

